version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: ProductService/ProductService.WebApi/Dockerfile
    container_name: product-service
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__EventStore=Host=postgres;Port=5432;Database=ProductDb;Username=postgres;Password=postgres
      - RabbitMQ__HostName=rabbitmq
    networks:
      - microservices-network

  inventory-service:
    build:
      context: .
      dockerfile: InventoryService/InventoryService.WebApi/Dockerfile
    container_name: inventory-service
    ports:
      - "5100:5100"
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - microservices-network

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ProductDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices-network

networks:
  microservices-network:

volumes:
  postgres_data:
  mongo_data: